/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ASNConnection
 */
public class ASNConnectionTest {
    private final ASNConnection model = new ASNConnection();

    /**
     * Model tests for ASNConnection
     */
    @Test
    public void testASNConnection() {
        // TODO: test ASNConnection
    }

    /**
     * Test the property 'asNumber'
     */
    @Test
    public void asNumberTest() {
        // TODO: test asNumber
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

}
