/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ASNResponseAsn
 */
public class ASNDetailsTest {
    private final ASNDetails model = new ASNDetails();

    /**
     * Model tests for ASNResponseAsn
     */
    @Test
    public void testASNResponseAsn() {
        // TODO: test ASNResponseAsn
    }

    /**
     * Test the property 'asNumber'
     */
    @Test
    public void asNumberTest() {
        // TODO: test asNumber
    }

    /**
     * Test the property 'organization'
     */
    @Test
    public void organizationTest() {
        // TODO: test organization
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'asnName'
     */
    @Test
    public void asnNameTest() {
        // TODO: test asnName
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'dateAllocated'
     */
    @Test
    public void dateAllocatedTest() {
        // TODO: test dateAllocated
    }

    /**
     * Test the property 'allocationStatus'
     */
    @Test
    public void allocationStatusTest() {
        // TODO: test allocationStatus
    }

    /**
     * Test the property 'numOfIpv4Routes'
     */
    @Test
    public void numOfIpv4RoutesTest() {
        // TODO: test numOfIpv4Routes
    }

    /**
     * Test the property 'numOfIpv6Routes'
     */
    @Test
    public void numOfIpv6RoutesTest() {
        // TODO: test numOfIpv6Routes
    }

    /**
     * Test the property 'rir'
     */
    @Test
    public void rirTest() {
        // TODO: test rir
    }

    /**
     * Test the property 'routes'
     */
    @Test
    public void routesTest() {
        // TODO: test routes
    }

    /**
     * Test the property 'upstreams'
     */
    @Test
    public void upstreamsTest() {
        // TODO: test upstreams
    }

    /**
     * Test the property 'downstreams'
     */
    @Test
    public void downstreamsTest() {
        // TODO: test downstreams
    }

    /**
     * Test the property 'peers'
     */
    @Test
    public void peersTest() {
        // TODO: test peers
    }

    /**
     * Test the property 'whoisResponse'
     */
    @Test
    public void whoisResponseTest() {
        // TODO: test whoisResponse
    }

}
