/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for AstronomyXMLResponse
 */
public class AstronomyXMLResponseTest {
    private final AstronomyXMLResponse model = new AstronomyXMLResponse();

    /**
     * Model tests for AstronomyXMLResponse
     */
    @Test
    public void testAstronomyXMLResponse() {
        // TODO: test AstronomyXMLResponse
    }

    /**
     * Test the property 'ip'
     */
    @Test
    public void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'astronomy'
     */
    @Test
    public void astronomyTest() {
        // TODO: test astronomy
    }

}
