/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for SecurityBulkPost200ResponseInner
 */
public class BulkSecurityResponseTest {
    private final BulkSecurityResponse model = new BulkSecurityResponse();

    /**
     * Model tests for SecurityBulkPost200ResponseInner
     */
    @Test
    public void testSecurityBulkPost200ResponseInner() {
        // TODO: test SecurityBulkPost200ResponseInner
    }

    /**
     * Test the property 'ip'
     */
    @Test
    public void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'hostname'
     */
    @Test
    public void hostnameTest() {
        // TODO: test hostname
    }

    /**
     * Test the property 'security'
     */
    @Test
    public void securityTest() {
        // TODO: test security
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'network'
     */
    @Test
    public void networkTest() {
        // TODO: test network
    }

    /**
     * Test the property 'timeZone'
     */
    @Test
    public void timeZoneTest() {
        // TODO: test timeZone
    }

    /**
     * Test the property 'userAgent'
     */
    @Test
    public void userAgentTest() {
        // TODO: test userAgent
    }

    /**
     * Test the property 'countryMetadata'
     */
    @Test
    public void countryMetadataTest() {
        // TODO: test countryMetadata
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
