/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for IpgeoBulkPostRequest
 */
public class BulkIPRequestTest {
    private final BulkIPRequest model = new BulkIPRequest();

    /**
     * Model tests for IpgeoBulkPostRequest
     */
    @Test
    public void testIpgeoBulkPostRequest() {
        // TODO: test IpgeoBulkPostRequest
    }

    /**
     * Test the property 'ips'
     */
    @Test
    public void ipsTest() {
        // TODO: test ips
    }

}
