/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CountryMetadata
 */
public class CountryMetadataTest {
    private final CountryMetadata model = new CountryMetadata();

    /**
     * Model tests for CountryMetadata
     */
    @Test
    public void testCountryMetadata() {
        // TODO: test CountryMetadata
    }

    /**
     * Test the property 'callingCode'
     */
    @Test
    public void callingCodeTest() {
        // TODO: test callingCode
    }

    /**
     * Test the property 'tld'
     */
    @Test
    public void tldTest() {
        // TODO: test tld
    }

    /**
     * Test the property 'languages'
     */
    @Test
    public void languagesTest() {
        // TODO: test languages
    }

}
