/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ErrorXMLResponse
 */
public class ErrorXMLResponseTest {
    private final ErrorXMLResponse model = new ErrorXMLResponse();

    /**
     * Model tests for ErrorXMLResponse
     */
    @Test
    public void testErrorXMLResponse() {
        // TODO: test ErrorXMLResponse
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
