/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for NetworkMinimalCompany
 */
public class NetworkMinimalCompanyTest {
    private final NetworkMinimalCompany model = new NetworkMinimalCompany();

    /**
     * Model tests for NetworkMinimalCompany
     */
    @Test
    public void testNetworkMinimalCompany() {
        // TODO: test NetworkMinimalCompany
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
