/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for NetworkMinimal
 */
public class NetworkMinimalTest {
    private final NetworkMinimal model = new NetworkMinimal();

    /**
     * Model tests for NetworkMinimal
     */
    @Test
    public void testNetworkMinimal() {
        // TODO: test NetworkMinimal
    }

    /**
     * Test the property 'asn'
     */
    @Test
    public void asnTest() {
        // TODO: test asn
    }

    /**
     * Test the property 'company'
     */
    @Test
    public void companyTest() {
        // TODO: test company
    }

}
