/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TimeConversionXMLResponse
 */
public class TimeConversionXMLResponseTest {
    private final TimeConversionXMLResponse model = new TimeConversionXMLResponse();

    /**
     * Model tests for TimeConversionXMLResponse
     */
    @Test
    public void testTimeConversionXMLResponse() {
        // TODO: test TimeConversionXMLResponse
    }

    /**
     * Test the property 'originalTime'
     */
    @Test
    public void originalTimeTest() {
        // TODO: test originalTime
    }

    /**
     * Test the property 'convertedTime'
     */
    @Test
    public void convertedTimeTest() {
        // TODO: test convertedTime
    }

    /**
     * Test the property 'diffHour'
     */
    @Test
    public void diffHourTest() {
        // TODO: test diffHour
    }

    /**
     * Test the property 'diffMin'
     */
    @Test
    public void diffMinTest() {
        // TODO: test diffMin
    }

}
