/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TimeZoneDetailedXMLResponse
 */
public class TimeZoneDetailedXMLResponseTest {
    private final TimeZoneDetailedXMLResponse model = new TimeZoneDetailedXMLResponse();

    /**
     * Model tests for TimeZoneDetailedXMLResponse
     */
    @Test
    public void testTimeZoneDetailedXMLResponse() {
        // TODO: test TimeZoneDetailedXMLResponse
    }

    /**
     * Test the property 'ip'
     */
    @Test
    public void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'airportDetails'
     */
    @Test
    public void airportDetailsTest() {
        // TODO: test airportDetails
    }

    /**
     * Test the property 'loCodeDetails'
     */
    @Test
    public void loCodeDetailsTest() {
        // TODO: test loCodeDetails
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'timeZone'
     */
    @Test
    public void timeZoneTest() {
        // TODO: test timeZone
    }

}
