/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TimezoneDetailDstEnd
 */
public class TimezoneDetailsDstEndTest {
    private final TimezoneDetailDstEnd model = new TimezoneDetailDstEnd();

    /**
     * Model tests for TimezoneDetailDstEnd
     */
    @Test
    public void testTimezoneDetailDstEnd() {
        // TODO: test TimezoneDetailDstEnd
    }

    /**
     * Test the property 'utcTime'
     */
    @Test
    public void utcTimeTest() {
        // TODO: test utcTime
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'gap'
     */
    @Test
    public void gapTest() {
        // TODO: test gap
    }

    /**
     * Test the property 'dateTimeAfter'
     */
    @Test
    public void dateTimeAfterTest() {
        // TODO: test dateTimeAfter
    }

    /**
     * Test the property 'dateTimeBefore'
     */
    @Test
    public void dateTimeBeforeTest() {
        // TODO: test dateTimeBefore
    }

    /**
     * Test the property 'overlap'
     */
    @Test
    public void overlapTest() {
        // TODO: test overlap
    }

}
