/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for UserAgentBulkPostRequest
 */
public class UserAgentBulkRequestTest {
    private final UserAgentBulkRequest model = new UserAgentBulkRequest();

    /**
     * Model tests for UserAgentBulkPostRequest
     */
    @Test
    public void testUserAgentBulkPostRequest() {
        // TODO: test UserAgentBulkPostRequest
    }

    /**
     * Test the property 'uaStrings'
     */
    @Test
    public void uaStringsTest() {
        // TODO: test uaStrings
    }

}
