/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for UserAgentDataEngine
 */
public class UserAgentDataEngineTest {
    private final UserAgentDataEngine model = new UserAgentDataEngine();

    /**
     * Model tests for UserAgentDataEngine
     */
    @Test
    public void testUserAgentDataEngine() {
        // TODO: test UserAgentDataEngine
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'versionMajor'
     */
    @Test
    public void versionMajorTest() {
        // TODO: test versionMajor
    }

}
