/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;


import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonElement;

import io.ipgeolocation.sdk.invoker.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class BulkGeolocationResponse extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(BulkGeolocationResponse.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!BulkGeolocationResponse.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'IpgeoBulkPost200ResponseInner' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ErrorResponse> adapterErrorResponse = gson.getDelegateAdapter(this, TypeToken.get(ErrorResponse.class));
            final TypeAdapter<GeolocationResponse> adapterGeolocationResponse = gson.getDelegateAdapter(this, TypeToken.get(GeolocationResponse.class));

            return (TypeAdapter<T>) new TypeAdapter<BulkGeolocationResponse>() {
                @Override
                public void write(JsonWriter out, BulkGeolocationResponse value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `ErrorResponse`
                    if (value.getActualInstance() instanceof ErrorResponse) {
                        JsonElement element = adapterErrorResponse.toJsonTree((ErrorResponse)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `GeolocationResponse`
                    if (value.getActualInstance() instanceof GeolocationResponse) {
                        JsonElement element = adapterGeolocationResponse.toJsonTree((GeolocationResponse)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: ErrorResponse, GeolocationResponse");
                }

                @Override
                public BulkGeolocationResponse read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize ErrorResponse
                    try {
                        // validate the JSON object to see if any exception is thrown
                        ErrorResponse.validateJsonElement(jsonElement);
                        actualAdapter = adapterErrorResponse;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'ErrorResponse'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for ErrorResponse failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'ErrorResponse'", e);
                    }
                    // deserialize GeolocationResponse
                    try {
                        // validate the JSON object to see if any exception is thrown
                        GeolocationResponse.validateJsonElement(jsonElement);
                        actualAdapter = adapterGeolocationResponse;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'GeolocationResponse'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for GeolocationResponse failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'GeolocationResponse'", e);
                    }

                    if (match == 1) {
                        BulkGeolocationResponse ret = new BulkGeolocationResponse();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for IpgeoBulkPost200ResponseInner: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public BulkGeolocationResponse() {
        super("oneOf", Boolean.FALSE);
    }

    public BulkGeolocationResponse(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("ErrorResponse", ErrorResponse.class);
        schemas.put("GeolocationResponse", GeolocationResponse.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return BulkGeolocationResponse.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * ErrorResponse, GeolocationResponse
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof ErrorResponse) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof GeolocationResponse) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be ErrorResponse, GeolocationResponse");
    }

    /**
     * Get the actual instance, which can be the following:
     * ErrorResponse, GeolocationResponse
     *
     * @return The actual instance (ErrorResponse, GeolocationResponse)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `ErrorResponse`. If the actual instance is not `ErrorResponse`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ErrorResponse`
     * @throws ClassCastException if the instance is not `ErrorResponse`
     */
    public ErrorResponse getErrorResponse() throws ClassCastException {
        return (ErrorResponse)super.getActualInstance();
    }

    /**
     * Get the actual instance of `GeolocationResponse`. If the actual instance is not `GeolocationResponse`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GeolocationResponse`
     * @throws ClassCastException if the instance is not `GeolocationResponse`
     */
    public GeolocationResponse getGeolocationResponse() throws ClassCastException {
        return (GeolocationResponse)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to IpgeoBulkPost200ResponseInner
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with ErrorResponse
        try {
            ErrorResponse.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for ErrorResponse failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with GeolocationResponse
        try {
            GeolocationResponse.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for GeolocationResponse failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for IpgeoBulkPost200ResponseInner with oneOf schemas: ErrorResponse, GeolocationResponse. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of IpgeoBulkPost200ResponseInner given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of IpgeoBulkPost200ResponseInner
     * @throws IOException if the JSON string is invalid with respect to IpgeoBulkPost200ResponseInner
     */
    public static BulkGeolocationResponse fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, BulkGeolocationResponse.class);
    }

    /**
     * Convert an instance of IpgeoBulkPost200ResponseInner to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

