/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import io.ipgeolocation.sdk.invoker.JSON;

/**
 * TimezoneLocation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class TimezoneLocation {
  public static final String SERIALIZED_NAME_LOCATION_STRING = "location_string";
  @SerializedName(SERIALIZED_NAME_LOCATION_STRING)
  @javax.annotation.Nullable
  private String locationString;

  public static final String SERIALIZED_NAME_CONTINENT_CODE = "continent_code";
  @SerializedName(SERIALIZED_NAME_CONTINENT_CODE)
  @javax.annotation.Nullable
  private String continentCode;

  public static final String SERIALIZED_NAME_CONTINENT_NAME = "continent_name";
  @SerializedName(SERIALIZED_NAME_CONTINENT_NAME)
  @javax.annotation.Nullable
  private String continentName;

  public static final String SERIALIZED_NAME_COUNTRY_CODE2 = "country_code2";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE2)
  @javax.annotation.Nullable
  private String countryCode2;

  public static final String SERIALIZED_NAME_COUNTRY_CODE3 = "country_code3";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE3)
  @javax.annotation.Nullable
  private String countryCode3;

  public static final String SERIALIZED_NAME_COUNTRY_NAME = "country_name";
  @SerializedName(SERIALIZED_NAME_COUNTRY_NAME)
  @javax.annotation.Nullable
  private String countryName;

  public static final String SERIALIZED_NAME_COUNTRY_NAME_OFFICIAL = "country_name_official";
  @SerializedName(SERIALIZED_NAME_COUNTRY_NAME_OFFICIAL)
  @javax.annotation.Nullable
  private String countryNameOfficial;

  public static final String SERIALIZED_NAME_IS_EU = "is_eu";
  @SerializedName(SERIALIZED_NAME_IS_EU)
  @javax.annotation.Nullable
  private Boolean isEu;

  public static final String SERIALIZED_NAME_STATE_PROV = "state_prov";
  @SerializedName(SERIALIZED_NAME_STATE_PROV)
  @javax.annotation.Nullable
  private String stateProv;

  public static final String SERIALIZED_NAME_STATE_CODE = "state_code";
  @SerializedName(SERIALIZED_NAME_STATE_CODE)
  @javax.annotation.Nullable
  private String stateCode;

  public static final String SERIALIZED_NAME_DISTRICT = "district";
  @SerializedName(SERIALIZED_NAME_DISTRICT)
  @javax.annotation.Nullable
  private String district;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  @javax.annotation.Nullable
  private String city;

  public static final String SERIALIZED_NAME_LOCALITY = "locality";
  @SerializedName(SERIALIZED_NAME_LOCALITY)
  @javax.annotation.Nullable
  private String locality;

  public static final String SERIALIZED_NAME_ZIPCODE = "zipcode";
  @SerializedName(SERIALIZED_NAME_ZIPCODE)
  @javax.annotation.Nullable
  private String zipcode;

  public static final String SERIALIZED_NAME_LATITUDE = "latitude";
  @SerializedName(SERIALIZED_NAME_LATITUDE)
  @javax.annotation.Nullable
  private String latitude;

  public static final String SERIALIZED_NAME_LONGITUDE = "longitude";
  @SerializedName(SERIALIZED_NAME_LONGITUDE)
  @javax.annotation.Nullable
  private String longitude;

  public TimezoneLocation() {
  }

  public TimezoneLocation locationString(@javax.annotation.Nullable String locationString) {
    this.locationString = locationString;
    return this;
  }

  /**
   * Get locationString
   * @return locationString
   */
  @javax.annotation.Nullable
  public String getLocationString() {
    return locationString;
  }

  public void setLocationString(@javax.annotation.Nullable String locationString) {
    this.locationString = locationString;
  }


  public TimezoneLocation continentCode(@javax.annotation.Nullable String continentCode) {
    this.continentCode = continentCode;
    return this;
  }

  /**
   * Get continentCode
   * @return continentCode
   */
  @javax.annotation.Nullable
  public String getContinentCode() {
    return continentCode;
  }

  public void setContinentCode(@javax.annotation.Nullable String continentCode) {
    this.continentCode = continentCode;
  }


  public TimezoneLocation continentName(@javax.annotation.Nullable String continentName) {
    this.continentName = continentName;
    return this;
  }

  /**
   * Get continentName
   * @return continentName
   */
  @javax.annotation.Nullable
  public String getContinentName() {
    return continentName;
  }

  public void setContinentName(@javax.annotation.Nullable String continentName) {
    this.continentName = continentName;
  }


  public TimezoneLocation countryCode2(@javax.annotation.Nullable String countryCode2) {
    this.countryCode2 = countryCode2;
    return this;
  }

  /**
   * Get countryCode2
   * @return countryCode2
   */
  @javax.annotation.Nullable
  public String getCountryCode2() {
    return countryCode2;
  }

  public void setCountryCode2(@javax.annotation.Nullable String countryCode2) {
    this.countryCode2 = countryCode2;
  }


  public TimezoneLocation countryCode3(@javax.annotation.Nullable String countryCode3) {
    this.countryCode3 = countryCode3;
    return this;
  }

  /**
   * Get countryCode3
   * @return countryCode3
   */
  @javax.annotation.Nullable
  public String getCountryCode3() {
    return countryCode3;
  }

  public void setCountryCode3(@javax.annotation.Nullable String countryCode3) {
    this.countryCode3 = countryCode3;
  }


  public TimezoneLocation countryName(@javax.annotation.Nullable String countryName) {
    this.countryName = countryName;
    return this;
  }

  /**
   * Get countryName
   * @return countryName
   */
  @javax.annotation.Nullable
  public String getCountryName() {
    return countryName;
  }

  public void setCountryName(@javax.annotation.Nullable String countryName) {
    this.countryName = countryName;
  }


  public TimezoneLocation countryNameOfficial(@javax.annotation.Nullable String countryNameOfficial) {
    this.countryNameOfficial = countryNameOfficial;
    return this;
  }

  /**
   * Get countryNameOfficial
   * @return countryNameOfficial
   */
  @javax.annotation.Nullable
  public String getCountryNameOfficial() {
    return countryNameOfficial;
  }

  public void setCountryNameOfficial(@javax.annotation.Nullable String countryNameOfficial) {
    this.countryNameOfficial = countryNameOfficial;
  }


  public TimezoneLocation isEu(@javax.annotation.Nullable Boolean isEu) {
    this.isEu = isEu;
    return this;
  }

  /**
   * Get isEu
   * @return isEu
   */
  @javax.annotation.Nullable
  public Boolean getIsEu() {
    return isEu;
  }

  public void setIsEu(@javax.annotation.Nullable Boolean isEu) {
    this.isEu = isEu;
  }


  public TimezoneLocation stateProv(@javax.annotation.Nullable String stateProv) {
    this.stateProv = stateProv;
    return this;
  }

  /**
   * Get stateProv
   * @return stateProv
   */
  @javax.annotation.Nullable
  public String getStateProv() {
    return stateProv;
  }

  public void setStateProv(@javax.annotation.Nullable String stateProv) {
    this.stateProv = stateProv;
  }


  public TimezoneLocation stateCode(@javax.annotation.Nullable String stateCode) {
    this.stateCode = stateCode;
    return this;
  }

  /**
   * Get stateCode
   * @return stateCode
   */
  @javax.annotation.Nullable
  public String getStateCode() {
    return stateCode;
  }

  public void setStateCode(@javax.annotation.Nullable String stateCode) {
    this.stateCode = stateCode;
  }


  public TimezoneLocation district(@javax.annotation.Nullable String district) {
    this.district = district;
    return this;
  }

  /**
   * Get district
   * @return district
   */
  @javax.annotation.Nullable
  public String getDistrict() {
    return district;
  }

  public void setDistrict(@javax.annotation.Nullable String district) {
    this.district = district;
  }


  public TimezoneLocation city(@javax.annotation.Nullable String city) {
    this.city = city;
    return this;
  }

  /**
   * Get city
   * @return city
   */
  @javax.annotation.Nullable
  public String getCity() {
    return city;
  }

  public void setCity(@javax.annotation.Nullable String city) {
    this.city = city;
  }


  public TimezoneLocation locality(@javax.annotation.Nullable String locality) {
    this.locality = locality;
    return this;
  }

  /**
   * Get locality
   * @return locality
   */
  @javax.annotation.Nullable
  public String getLocality() {
    return locality;
  }

  public void setLocality(@javax.annotation.Nullable String locality) {
    this.locality = locality;
  }


  public TimezoneLocation zipcode(@javax.annotation.Nullable String zipcode) {
    this.zipcode = zipcode;
    return this;
  }

  /**
   * Get zipcode
   * @return zipcode
   */
  @javax.annotation.Nullable
  public String getZipcode() {
    return zipcode;
  }

  public void setZipcode(@javax.annotation.Nullable String zipcode) {
    this.zipcode = zipcode;
  }


  public TimezoneLocation latitude(@javax.annotation.Nullable String latitude) {
    this.latitude = latitude;
    return this;
  }

  /**
   * Get latitude
   * @return latitude
   */
  @javax.annotation.Nullable
  public String getLatitude() {
    return latitude;
  }

  public void setLatitude(@javax.annotation.Nullable String latitude) {
    this.latitude = latitude;
  }


  public TimezoneLocation longitude(@javax.annotation.Nullable String longitude) {
    this.longitude = longitude;
    return this;
  }

  /**
   * Get longitude
   * @return longitude
   */
  @javax.annotation.Nullable
  public String getLongitude() {
    return longitude;
  }

  public void setLongitude(@javax.annotation.Nullable String longitude) {
    this.longitude = longitude;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimezoneLocation timezoneLocation = (TimezoneLocation) o;
    return Objects.equals(this.locationString, timezoneLocation.locationString) &&
        Objects.equals(this.continentCode, timezoneLocation.continentCode) &&
        Objects.equals(this.continentName, timezoneLocation.continentName) &&
        Objects.equals(this.countryCode2, timezoneLocation.countryCode2) &&
        Objects.equals(this.countryCode3, timezoneLocation.countryCode3) &&
        Objects.equals(this.countryName, timezoneLocation.countryName) &&
        Objects.equals(this.countryNameOfficial, timezoneLocation.countryNameOfficial) &&
        Objects.equals(this.isEu, timezoneLocation.isEu) &&
        Objects.equals(this.stateProv, timezoneLocation.stateProv) &&
        Objects.equals(this.stateCode, timezoneLocation.stateCode) &&
        Objects.equals(this.district, timezoneLocation.district) &&
        Objects.equals(this.city, timezoneLocation.city) &&
        Objects.equals(this.locality, timezoneLocation.locality) &&
        Objects.equals(this.zipcode, timezoneLocation.zipcode) &&
        Objects.equals(this.latitude, timezoneLocation.latitude) &&
        Objects.equals(this.longitude, timezoneLocation.longitude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locationString, continentCode, continentName, countryCode2, countryCode3, countryName, countryNameOfficial, isEu, stateProv, stateCode, district, city, locality, zipcode, latitude, longitude);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimezoneLocation {\n");
    sb.append("    locationString: ").append(toIndentedString(locationString)).append("\n");
    sb.append("    continentCode: ").append(toIndentedString(continentCode)).append("\n");
    sb.append("    continentName: ").append(toIndentedString(continentName)).append("\n");
    sb.append("    countryCode2: ").append(toIndentedString(countryCode2)).append("\n");
    sb.append("    countryCode3: ").append(toIndentedString(countryCode3)).append("\n");
    sb.append("    countryName: ").append(toIndentedString(countryName)).append("\n");
    sb.append("    countryNameOfficial: ").append(toIndentedString(countryNameOfficial)).append("\n");
    sb.append("    isEu: ").append(toIndentedString(isEu)).append("\n");
    sb.append("    stateProv: ").append(toIndentedString(stateProv)).append("\n");
    sb.append("    stateCode: ").append(toIndentedString(stateCode)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    locality: ").append(toIndentedString(locality)).append("\n");
    sb.append("    zipcode: ").append(toIndentedString(zipcode)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("location_string");
    openapiFields.add("continent_code");
    openapiFields.add("continent_name");
    openapiFields.add("country_code2");
    openapiFields.add("country_code3");
    openapiFields.add("country_name");
    openapiFields.add("country_name_official");
    openapiFields.add("is_eu");
    openapiFields.add("state_prov");
    openapiFields.add("state_code");
    openapiFields.add("district");
    openapiFields.add("city");
    openapiFields.add("locality");
    openapiFields.add("zipcode");
    openapiFields.add("latitude");
    openapiFields.add("longitude");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TimezoneLocation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TimezoneLocation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TimezoneLocation is not found in the empty JSON string", TimezoneLocation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TimezoneLocation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TimezoneLocation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("location_string") != null && !jsonObj.get("location_string").isJsonNull()) && !jsonObj.get("location_string").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `location_string` to be a primitive type in the JSON string but got `%s`", jsonObj.get("location_string").toString()));
      }
      if ((jsonObj.get("continent_code") != null && !jsonObj.get("continent_code").isJsonNull()) && !jsonObj.get("continent_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `continent_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("continent_code").toString()));
      }
      if ((jsonObj.get("continent_name") != null && !jsonObj.get("continent_name").isJsonNull()) && !jsonObj.get("continent_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `continent_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("continent_name").toString()));
      }
      if ((jsonObj.get("country_code2") != null && !jsonObj.get("country_code2").isJsonNull()) && !jsonObj.get("country_code2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `country_code2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country_code2").toString()));
      }
      if ((jsonObj.get("country_code3") != null && !jsonObj.get("country_code3").isJsonNull()) && !jsonObj.get("country_code3").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `country_code3` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country_code3").toString()));
      }
      if ((jsonObj.get("country_name") != null && !jsonObj.get("country_name").isJsonNull()) && !jsonObj.get("country_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `country_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country_name").toString()));
      }
      if ((jsonObj.get("country_name_official") != null && !jsonObj.get("country_name_official").isJsonNull()) && !jsonObj.get("country_name_official").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `country_name_official` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country_name_official").toString()));
      }
      if ((jsonObj.get("state_prov") != null && !jsonObj.get("state_prov").isJsonNull()) && !jsonObj.get("state_prov").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `state_prov` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state_prov").toString()));
      }
      if ((jsonObj.get("state_code") != null && !jsonObj.get("state_code").isJsonNull()) && !jsonObj.get("state_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `state_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state_code").toString()));
      }
      if ((jsonObj.get("district") != null && !jsonObj.get("district").isJsonNull()) && !jsonObj.get("district").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `district` to be a primitive type in the JSON string but got `%s`", jsonObj.get("district").toString()));
      }
      if ((jsonObj.get("city") != null && !jsonObj.get("city").isJsonNull()) && !jsonObj.get("city").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `city` to be a primitive type in the JSON string but got `%s`", jsonObj.get("city").toString()));
      }
      if ((jsonObj.get("locality") != null && !jsonObj.get("locality").isJsonNull()) && !jsonObj.get("locality").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `locality` to be a primitive type in the JSON string but got `%s`", jsonObj.get("locality").toString()));
      }
      if ((jsonObj.get("zipcode") != null && !jsonObj.get("zipcode").isJsonNull()) && !jsonObj.get("zipcode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `zipcode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("zipcode").toString()));
      }
      if ((jsonObj.get("latitude") != null && !jsonObj.get("latitude").isJsonNull()) && !jsonObj.get("latitude").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `latitude` to be a primitive type in the JSON string but got `%s`", jsonObj.get("latitude").toString()));
      }
      if ((jsonObj.get("longitude") != null && !jsonObj.get("longitude").isJsonNull()) && !jsonObj.get("longitude").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `longitude` to be a primitive type in the JSON string but got `%s`", jsonObj.get("longitude").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TimezoneLocation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TimezoneLocation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TimezoneLocation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TimezoneLocation.class));

       return (TypeAdapter<T>) new TypeAdapter<TimezoneLocation>() {
           @Override
           public void write(JsonWriter out, TimezoneLocation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TimezoneLocation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TimezoneLocation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TimezoneLocation
   * @throws IOException if the JSON string is invalid with respect to TimezoneLocation
   */
  public static TimezoneLocation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TimezoneLocation.class);
  }

  /**
   * Convert an instance of TimezoneLocation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

