/*
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ipgeolocation.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import io.ipgeolocation.sdk.invoker.JSON;

/**
 * UserAgentData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class UserAgentData {
  public static final String SERIALIZED_NAME_USER_AGENT_STRING = "user_agent_string";
  @SerializedName(SERIALIZED_NAME_USER_AGENT_STRING)
  @javax.annotation.Nullable
  private String userAgentString;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private String type;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nullable
  private String version;

  public static final String SERIALIZED_NAME_VERSION_MAJOR = "version_major";
  @SerializedName(SERIALIZED_NAME_VERSION_MAJOR)
  @javax.annotation.Nullable
  private String versionMajor;

  public static final String SERIALIZED_NAME_DEVICE = "device";
  @SerializedName(SERIALIZED_NAME_DEVICE)
  @javax.annotation.Nullable
  private UserAgentDataDevice device;

  public static final String SERIALIZED_NAME_ENGINE = "engine";
  @SerializedName(SERIALIZED_NAME_ENGINE)
  @javax.annotation.Nullable
  private UserAgentDataEngine engine;

  public static final String SERIALIZED_NAME_OPERATING_SYSTEM = "operating_system";
  @SerializedName(SERIALIZED_NAME_OPERATING_SYSTEM)
  @javax.annotation.Nullable
  private UserAgentDataOperatingSystem operatingSystem;

  public UserAgentData() {
  }

  public UserAgentData userAgentString(@javax.annotation.Nullable String userAgentString) {
    this.userAgentString = userAgentString;
    return this;
  }

  /**
   * Get userAgentString
   * @return userAgentString
   */
  @javax.annotation.Nullable
  public String getUserAgentString() {
    return userAgentString;
  }

  public void setUserAgentString(@javax.annotation.Nullable String userAgentString) {
    this.userAgentString = userAgentString;
  }


  public UserAgentData name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public UserAgentData type(@javax.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }


  public UserAgentData version(@javax.annotation.Nullable String version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  public String getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nullable String version) {
    this.version = version;
  }


  public UserAgentData versionMajor(@javax.annotation.Nullable String versionMajor) {
    this.versionMajor = versionMajor;
    return this;
  }

  /**
   * Get versionMajor
   * @return versionMajor
   */
  @javax.annotation.Nullable
  public String getVersionMajor() {
    return versionMajor;
  }

  public void setVersionMajor(@javax.annotation.Nullable String versionMajor) {
    this.versionMajor = versionMajor;
  }


  public UserAgentData device(@javax.annotation.Nullable UserAgentDataDevice device) {
    this.device = device;
    return this;
  }

  /**
   * Get device
   * @return device
   */
  @javax.annotation.Nullable
  public UserAgentDataDevice getDevice() {
    return device;
  }

  public void setDevice(@javax.annotation.Nullable UserAgentDataDevice device) {
    this.device = device;
  }


  public UserAgentData engine(@javax.annotation.Nullable UserAgentDataEngine engine) {
    this.engine = engine;
    return this;
  }

  /**
   * Get engine
   * @return engine
   */
  @javax.annotation.Nullable
  public UserAgentDataEngine getEngine() {
    return engine;
  }

  public void setEngine(@javax.annotation.Nullable UserAgentDataEngine engine) {
    this.engine = engine;
  }


  public UserAgentData operatingSystem(@javax.annotation.Nullable UserAgentDataOperatingSystem operatingSystem) {
    this.operatingSystem = operatingSystem;
    return this;
  }

  /**
   * Get operatingSystem
   * @return operatingSystem
   */
  @javax.annotation.Nullable
  public UserAgentDataOperatingSystem getOperatingSystem() {
    return operatingSystem;
  }

  public void setOperatingSystem(@javax.annotation.Nullable UserAgentDataOperatingSystem operatingSystem) {
    this.operatingSystem = operatingSystem;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAgentData userAgentData = (UserAgentData) o;
    return Objects.equals(this.userAgentString, userAgentData.userAgentString) &&
        Objects.equals(this.name, userAgentData.name) &&
        Objects.equals(this.type, userAgentData.type) &&
        Objects.equals(this.version, userAgentData.version) &&
        Objects.equals(this.versionMajor, userAgentData.versionMajor) &&
        Objects.equals(this.device, userAgentData.device) &&
        Objects.equals(this.engine, userAgentData.engine) &&
        Objects.equals(this.operatingSystem, userAgentData.operatingSystem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userAgentString, name, type, version, versionMajor, device, engine, operatingSystem);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAgentData {\n");
    sb.append("    userAgentString: ").append(toIndentedString(userAgentString)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    versionMajor: ").append(toIndentedString(versionMajor)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    engine: ").append(toIndentedString(engine)).append("\n");
    sb.append("    operatingSystem: ").append(toIndentedString(operatingSystem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("user_agent_string");
    openapiFields.add("name");
    openapiFields.add("type");
    openapiFields.add("version");
    openapiFields.add("version_major");
    openapiFields.add("device");
    openapiFields.add("engine");
    openapiFields.add("operating_system");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UserAgentData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UserAgentData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UserAgentData is not found in the empty JSON string", UserAgentData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UserAgentData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UserAgentData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("user_agent_string") != null && !jsonObj.get("user_agent_string").isJsonNull()) && !jsonObj.get("user_agent_string").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `user_agent_string` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_agent_string").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("version") != null && !jsonObj.get("version").isJsonNull()) && !jsonObj.get("version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("version").toString()));
      }
      if ((jsonObj.get("version_major") != null && !jsonObj.get("version_major").isJsonNull()) && !jsonObj.get("version_major").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `version_major` to be a primitive type in the JSON string but got `%s`", jsonObj.get("version_major").toString()));
      }
      // validate the optional field `device`
      if (jsonObj.get("device") != null && !jsonObj.get("device").isJsonNull()) {
        UserAgentDataDevice.validateJsonElement(jsonObj.get("device"));
      }
      // validate the optional field `engine`
      if (jsonObj.get("engine") != null && !jsonObj.get("engine").isJsonNull()) {
        UserAgentDataEngine.validateJsonElement(jsonObj.get("engine"));
      }
      // validate the optional field `operating_system`
      if (jsonObj.get("operating_system") != null && !jsonObj.get("operating_system").isJsonNull()) {
        UserAgentDataOperatingSystem.validateJsonElement(jsonObj.get("operating_system"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UserAgentData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UserAgentData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UserAgentData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UserAgentData.class));

       return (TypeAdapter<T>) new TypeAdapter<UserAgentData>() {
           @Override
           public void write(JsonWriter out, UserAgentData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UserAgentData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UserAgentData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UserAgentData
   * @throws IOException if the JSON string is invalid with respect to UserAgentData
   */
  public static UserAgentData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UserAgentData.class);
  }

  /**
   * Convert an instance of UserAgentData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

